PREFIX adr: <http://kg.artsdata.ca/resource/>
PREFIX schema: <http://schema.org/>
construct {
    adr:K11-22 ?p ?o ;
    schema:address ?address .
    ?address ?address_pred ?address_obj .
} where {
    graph ?g {
        adr:K11-22 ?p ?o ;
        schema:address ?address .
        ?address ?address_pred ?address_obj .
    }
}