# This SPARQL adds the EventSeries url to the AggregateOffer 
# when there are no urls inside the offers
# which can happend when shows (at Place des arts) are sold out!

PREFIX adr: <http://kg.artsdata.ca/resource/>
PREFIX schema: <http://schema.org/>

insert {
  ?AggregateOffer schema:url ?event_url .
}
where {
  ?event a schema:EventSeries ; 
    schema:url ?event_url ; 
    schema:subEvent ?subEvent .
  ?subEvent a schema:Event ;
    schema:offers ?AggregateOffer .
  FILTER NOT EXISTS {  ?AggregateOffer schema:url ?any_url  }
 
} 