PREFIX schema: <http://schema.org/>
construct {
    ?uri ?p  ?o .
    ?o ?op ?oo .
    ?oo ?oop ?ooo .
    
}
from <http://kg.artsdata.ca/minted/K5>
where {

      ?uri a schema:Organization .
      ?uri ?p  ?o .
      OPTIONAL {
          ?o ?op ?oo .
      }
      OPTIONAL {
          ?o ?op ?oo .
          ?oo ?oop ?ooo .
      }
 
} limit 10 offset 0