# This SPARQL removes artificial schema:AggregateOffer
# created by Footlight Console
# unless it is the only single type of offer
# Github issue redefines the Offer data model to which
# both Artsdata and Footlight Console will eventually use.
# Until then this SPARQL is needed.

PREFIX schema: <http://schema.org/>
delete {
  ?e schema:offers ?offer .
  ?offer ?p ?o .
}
where
{
  {  select ?e where {
      ?e schema:offers ?offer .
    } group by ?e having(count(?offer) > 1)
  } 
  ?e schema:offers ?offer .
  ?offer a schema:AggregateOffer;
    schema:additionalType ?type ;
    ?p ?o .
} 
