PREFIX adr: <http://kg.artsdata.ca/resource/>
PREFIX schema: <http://schema.org/>
construct {
    ?uri ?p ?o ;
    schema:address ?address .
    ?address ?address_pred ?address_obj .
} where {
    values ?uri { <uri_list_placeholder> }

    graph ?g {
        ?uri ?p ?o .
        OPTIONAL {
            ?uri  schema:address ?address .
            ?address ?address_pred ?address_obj .
        }
        filter(!isBLANK(?o))
    } 
}